### ISSUE TITLE
Support Flask 1.0.0+

### ISSUE THREAD

**Issue by dbanty** [anurag90x/flask-pundit#4]
Hello,

I was just about to try using Flask-pundit which looks amazing and exactly what I've been searching for.  However, I'm using Flask 1.0.2 which pip thinks is incompatible with this extension.  I see you already changed the requirements to the new version of Flask, will you be uploading a release soon with this support?

Thanks!

**Comment by anurag90x** [comment]
Hi,
I'd be happy to release a version today. I'll update this issue when I do.

Thanks

**Comment by dbanty** [comment]
I just realized that the setup.py also has a "requirements" section pointing to the older Flask, so that will have to be updated too.  Found that out when I tried to install from Git.

Thanks again!

**Comment by anurag90x** [comment]
@dbanty I've merged your changes and released a new version. Thanks!
